'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WebPrinter
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PrinterDocument_Binding", [Namespace]:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument")>  _
    Partial Public Class PrinterDocument
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private Etiquetas_EnviosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Etiquetas_GS1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Etiquetas_Kits_GS1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Etiquetas_KitsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GTIN14_DCOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Impresion_AlbaranOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Impresion_EnvioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Impresion_Etiqueta_Kit_EspecialOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Impresion_Etiqueta_KitOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Impresion_Etiquetas_EnvioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Impresion_GS1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Impresion_Hoja_Kit_RegistradaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Impresion_Hoja_KitOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Pendiente_PDFOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Printer_LabelOperationCompleted As System.Threading.SendOrPostCallback
        
        Private resolverOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Printer_Task.My.MySettings.Default.Printer_Task_WebPrinter_PrinterDocument
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event Etiquetas_EnviosCompleted As Etiquetas_EnviosCompletedEventHandler
        
        '''<remarks/>
        Public Event Etiquetas_GS1Completed As Etiquetas_GS1CompletedEventHandler
        
        '''<remarks/>
        Public Event Etiquetas_Kits_GS1Completed As Etiquetas_Kits_GS1CompletedEventHandler
        
        '''<remarks/>
        Public Event Etiquetas_KitsCompleted As Etiquetas_KitsCompletedEventHandler
        
        '''<remarks/>
        Public Event GTIN14_DCCompleted As GTIN14_DCCompletedEventHandler
        
        '''<remarks/>
        Public Event Impresion_AlbaranCompleted As Impresion_AlbaranCompletedEventHandler
        
        '''<remarks/>
        Public Event Impresion_EnvioCompleted As Impresion_EnvioCompletedEventHandler
        
        '''<remarks/>
        Public Event Impresion_Etiqueta_Kit_EspecialCompleted As Impresion_Etiqueta_Kit_EspecialCompletedEventHandler
        
        '''<remarks/>
        Public Event Impresion_Etiqueta_KitCompleted As Impresion_Etiqueta_KitCompletedEventHandler
        
        '''<remarks/>
        Public Event Impresion_Etiquetas_EnvioCompleted As Impresion_Etiquetas_EnvioCompletedEventHandler
        
        '''<remarks/>
        Public Event Impresion_GS1Completed As Impresion_GS1CompletedEventHandler
        
        '''<remarks/>
        Public Event Impresion_Hoja_Kit_RegistradaCompleted As Impresion_Hoja_Kit_RegistradaCompletedEventHandler
        
        '''<remarks/>
        Public Event Impresion_Hoja_KitCompleted As Impresion_Hoja_KitCompletedEventHandler
        
        '''<remarks/>
        Public Event Pendiente_PDFCompleted As Pendiente_PDFCompletedEventHandler
        
        '''<remarks/>
        Public Event Printer_LabelCompleted As Printer_LabelCompletedEventHandler
        
        '''<remarks/>
        Public Event resolverCompleted As resolverCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrinterDocument:Etiquetas_Envios", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", ResponseElementName:="Etiquetas_Envios_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Etiquetas_Envios() As <System.Xml.Serialization.XmlElementAttribute("return_value")> String
            Dim results() As Object = Me.Invoke("Etiquetas_Envios", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Etiquetas_EnviosAsync()
            Me.Etiquetas_EnviosAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Etiquetas_EnviosAsync(ByVal userState As Object)
            If (Me.Etiquetas_EnviosOperationCompleted Is Nothing) Then
                Me.Etiquetas_EnviosOperationCompleted = AddressOf Me.OnEtiquetas_EnviosOperationCompleted
            End If
            Me.InvokeAsync("Etiquetas_Envios", New Object(-1) {}, Me.Etiquetas_EnviosOperationCompleted, userState)
        End Sub
        
        Private Sub OnEtiquetas_EnviosOperationCompleted(ByVal arg As Object)
            If (Not (Me.Etiquetas_EnviosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Etiquetas_EnviosCompleted(Me, New Etiquetas_EnviosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrinterDocument:Etiquetas_GS1", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", ResponseElementName:="Etiquetas_GS1_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Etiquetas_GS1() As <System.Xml.Serialization.XmlElementAttribute("return_value")> String
            Dim results() As Object = Me.Invoke("Etiquetas_GS1", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Etiquetas_GS1Async()
            Me.Etiquetas_GS1Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Etiquetas_GS1Async(ByVal userState As Object)
            If (Me.Etiquetas_GS1OperationCompleted Is Nothing) Then
                Me.Etiquetas_GS1OperationCompleted = AddressOf Me.OnEtiquetas_GS1OperationCompleted
            End If
            Me.InvokeAsync("Etiquetas_GS1", New Object(-1) {}, Me.Etiquetas_GS1OperationCompleted, userState)
        End Sub
        
        Private Sub OnEtiquetas_GS1OperationCompleted(ByVal arg As Object)
            If (Not (Me.Etiquetas_GS1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Etiquetas_GS1Completed(Me, New Etiquetas_GS1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrinterDocument:Etiquetas_Kits_GS1", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", ResponseElementName:="Etiquetas_Kits_GS1_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Etiquetas_Kits_GS1() As <System.Xml.Serialization.XmlElementAttribute("return_value")> String
            Dim results() As Object = Me.Invoke("Etiquetas_Kits_GS1", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Etiquetas_Kits_GS1Async()
            Me.Etiquetas_Kits_GS1Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Etiquetas_Kits_GS1Async(ByVal userState As Object)
            If (Me.Etiquetas_Kits_GS1OperationCompleted Is Nothing) Then
                Me.Etiquetas_Kits_GS1OperationCompleted = AddressOf Me.OnEtiquetas_Kits_GS1OperationCompleted
            End If
            Me.InvokeAsync("Etiquetas_Kits_GS1", New Object(-1) {}, Me.Etiquetas_Kits_GS1OperationCompleted, userState)
        End Sub
        
        Private Sub OnEtiquetas_Kits_GS1OperationCompleted(ByVal arg As Object)
            If (Not (Me.Etiquetas_Kits_GS1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Etiquetas_Kits_GS1Completed(Me, New Etiquetas_Kits_GS1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrinterDocument:Etiquetas_Kits", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", ResponseElementName:="Etiquetas_Kits_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Etiquetas_Kits() As <System.Xml.Serialization.XmlElementAttribute("return_value")> String
            Dim results() As Object = Me.Invoke("Etiquetas_Kits", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Etiquetas_KitsAsync()
            Me.Etiquetas_KitsAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Etiquetas_KitsAsync(ByVal userState As Object)
            If (Me.Etiquetas_KitsOperationCompleted Is Nothing) Then
                Me.Etiquetas_KitsOperationCompleted = AddressOf Me.OnEtiquetas_KitsOperationCompleted
            End If
            Me.InvokeAsync("Etiquetas_Kits", New Object(-1) {}, Me.Etiquetas_KitsOperationCompleted, userState)
        End Sub
        
        Private Sub OnEtiquetas_KitsOperationCompleted(ByVal arg As Object)
            If (Not (Me.Etiquetas_KitsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Etiquetas_KitsCompleted(Me, New Etiquetas_KitsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrinterDocument:GTIN14_DC", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", ResponseElementName:="GTIN14_DC_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GTIN14_DC(ByVal numero As String) As <System.Xml.Serialization.XmlElementAttribute("return_value")> String
            Dim results() As Object = Me.Invoke("GTIN14_DC", New Object() {numero})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GTIN14_DCAsync(ByVal numero As String)
            Me.GTIN14_DCAsync(numero, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GTIN14_DCAsync(ByVal numero As String, ByVal userState As Object)
            If (Me.GTIN14_DCOperationCompleted Is Nothing) Then
                Me.GTIN14_DCOperationCompleted = AddressOf Me.OnGTIN14_DCOperationCompleted
            End If
            Me.InvokeAsync("GTIN14_DC", New Object() {numero}, Me.GTIN14_DCOperationCompleted, userState)
        End Sub
        
        Private Sub OnGTIN14_DCOperationCompleted(ByVal arg As Object)
            If (Not (Me.GTIN14_DCCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GTIN14_DCCompleted(Me, New GTIN14_DCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrinterDocument:Impresion_Albaran", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", ResponseElementName:="Impresion_Albaran_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Impresion_Albaran(ByVal documentoNo As String)
            Me.Invoke("Impresion_Albaran", New Object() {documentoNo})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Impresion_AlbaranAsync(ByVal documentoNo As String)
            Me.Impresion_AlbaranAsync(documentoNo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Impresion_AlbaranAsync(ByVal documentoNo As String, ByVal userState As Object)
            If (Me.Impresion_AlbaranOperationCompleted Is Nothing) Then
                Me.Impresion_AlbaranOperationCompleted = AddressOf Me.OnImpresion_AlbaranOperationCompleted
            End If
            Me.InvokeAsync("Impresion_Albaran", New Object() {documentoNo}, Me.Impresion_AlbaranOperationCompleted, userState)
        End Sub
        
        Private Sub OnImpresion_AlbaranOperationCompleted(ByVal arg As Object)
            If (Not (Me.Impresion_AlbaranCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Impresion_AlbaranCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrinterDocument:Impresion_Envio", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", ResponseElementName:="Impresion_Envio_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Impresion_Envio(ByVal envioNo As String)
            Me.Invoke("Impresion_Envio", New Object() {envioNo})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Impresion_EnvioAsync(ByVal envioNo As String)
            Me.Impresion_EnvioAsync(envioNo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Impresion_EnvioAsync(ByVal envioNo As String, ByVal userState As Object)
            If (Me.Impresion_EnvioOperationCompleted Is Nothing) Then
                Me.Impresion_EnvioOperationCompleted = AddressOf Me.OnImpresion_EnvioOperationCompleted
            End If
            Me.InvokeAsync("Impresion_Envio", New Object() {envioNo}, Me.Impresion_EnvioOperationCompleted, userState)
        End Sub
        
        Private Sub OnImpresion_EnvioOperationCompleted(ByVal arg As Object)
            If (Not (Me.Impresion_EnvioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Impresion_EnvioCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrinterDocument:Impresion_Etiqueta_Kit_Es"& _ 
            "pecial", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", ResponseElementName:="Impresion_Etiqueta_Kit_Especial_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Impresion_Etiqueta_Kit_Especial(ByVal assNo As String, ByVal copias As Integer, ByVal unidades As Integer)
            Me.Invoke("Impresion_Etiqueta_Kit_Especial", New Object() {assNo, copias, unidades})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Impresion_Etiqueta_Kit_EspecialAsync(ByVal assNo As String, ByVal copias As Integer, ByVal unidades As Integer)
            Me.Impresion_Etiqueta_Kit_EspecialAsync(assNo, copias, unidades, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Impresion_Etiqueta_Kit_EspecialAsync(ByVal assNo As String, ByVal copias As Integer, ByVal unidades As Integer, ByVal userState As Object)
            If (Me.Impresion_Etiqueta_Kit_EspecialOperationCompleted Is Nothing) Then
                Me.Impresion_Etiqueta_Kit_EspecialOperationCompleted = AddressOf Me.OnImpresion_Etiqueta_Kit_EspecialOperationCompleted
            End If
            Me.InvokeAsync("Impresion_Etiqueta_Kit_Especial", New Object() {assNo, copias, unidades}, Me.Impresion_Etiqueta_Kit_EspecialOperationCompleted, userState)
        End Sub
        
        Private Sub OnImpresion_Etiqueta_Kit_EspecialOperationCompleted(ByVal arg As Object)
            If (Not (Me.Impresion_Etiqueta_Kit_EspecialCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Impresion_Etiqueta_Kit_EspecialCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrinterDocument:Impresion_Etiqueta_Kit", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", ResponseElementName:="Impresion_Etiqueta_Kit_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Impresion_Etiqueta_Kit(ByVal assNo As String, ByVal copias As Integer, ByVal unidades As Integer)
            Me.Invoke("Impresion_Etiqueta_Kit", New Object() {assNo, copias, unidades})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Impresion_Etiqueta_KitAsync(ByVal assNo As String, ByVal copias As Integer, ByVal unidades As Integer)
            Me.Impresion_Etiqueta_KitAsync(assNo, copias, unidades, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Impresion_Etiqueta_KitAsync(ByVal assNo As String, ByVal copias As Integer, ByVal unidades As Integer, ByVal userState As Object)
            If (Me.Impresion_Etiqueta_KitOperationCompleted Is Nothing) Then
                Me.Impresion_Etiqueta_KitOperationCompleted = AddressOf Me.OnImpresion_Etiqueta_KitOperationCompleted
            End If
            Me.InvokeAsync("Impresion_Etiqueta_Kit", New Object() {assNo, copias, unidades}, Me.Impresion_Etiqueta_KitOperationCompleted, userState)
        End Sub
        
        Private Sub OnImpresion_Etiqueta_KitOperationCompleted(ByVal arg As Object)
            If (Not (Me.Impresion_Etiqueta_KitCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Impresion_Etiqueta_KitCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrinterDocument:Impresion_Etiquetas_Envio"& _ 
            "", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", ResponseElementName:="Impresion_Etiquetas_Envio_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Impresion_Etiquetas_Envio(ByVal customerNo As String, ByVal shipCode As String, ByVal copias As Integer, ByVal impresora As String)
            Me.Invoke("Impresion_Etiquetas_Envio", New Object() {customerNo, shipCode, copias, impresora})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Impresion_Etiquetas_EnvioAsync(ByVal customerNo As String, ByVal shipCode As String, ByVal copias As Integer, ByVal impresora As String)
            Me.Impresion_Etiquetas_EnvioAsync(customerNo, shipCode, copias, impresora, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Impresion_Etiquetas_EnvioAsync(ByVal customerNo As String, ByVal shipCode As String, ByVal copias As Integer, ByVal impresora As String, ByVal userState As Object)
            If (Me.Impresion_Etiquetas_EnvioOperationCompleted Is Nothing) Then
                Me.Impresion_Etiquetas_EnvioOperationCompleted = AddressOf Me.OnImpresion_Etiquetas_EnvioOperationCompleted
            End If
            Me.InvokeAsync("Impresion_Etiquetas_Envio", New Object() {customerNo, shipCode, copias, impresora}, Me.Impresion_Etiquetas_EnvioOperationCompleted, userState)
        End Sub
        
        Private Sub OnImpresion_Etiquetas_EnvioOperationCompleted(ByVal arg As Object)
            If (Not (Me.Impresion_Etiquetas_EnvioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Impresion_Etiquetas_EnvioCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrinterDocument:Impresion_GS1", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", ResponseElementName:="Impresion_GS1_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Impresion_GS1(ByVal referencia As String, ByVal lote As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> ByVal caducidad As Date, ByVal copias As Integer, ByVal impresora As String)
            Me.Invoke("Impresion_GS1", New Object() {referencia, lote, caducidad, copias, impresora})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Impresion_GS1Async(ByVal referencia As String, ByVal lote As String, ByVal caducidad As Date, ByVal copias As Integer, ByVal impresora As String)
            Me.Impresion_GS1Async(referencia, lote, caducidad, copias, impresora, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Impresion_GS1Async(ByVal referencia As String, ByVal lote As String, ByVal caducidad As Date, ByVal copias As Integer, ByVal impresora As String, ByVal userState As Object)
            If (Me.Impresion_GS1OperationCompleted Is Nothing) Then
                Me.Impresion_GS1OperationCompleted = AddressOf Me.OnImpresion_GS1OperationCompleted
            End If
            Me.InvokeAsync("Impresion_GS1", New Object() {referencia, lote, caducidad, copias, impresora}, Me.Impresion_GS1OperationCompleted, userState)
        End Sub
        
        Private Sub OnImpresion_GS1OperationCompleted(ByVal arg As Object)
            If (Not (Me.Impresion_GS1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Impresion_GS1Completed(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrinterDocument:Impresion_Hoja_Kit_Regist"& _ 
            "rada", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", ResponseElementName:="Impresion_Hoja_Kit_Registrada_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Impresion_Hoja_Kit_Registrada(ByVal assNo As String)
            Me.Invoke("Impresion_Hoja_Kit_Registrada", New Object() {assNo})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Impresion_Hoja_Kit_RegistradaAsync(ByVal assNo As String)
            Me.Impresion_Hoja_Kit_RegistradaAsync(assNo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Impresion_Hoja_Kit_RegistradaAsync(ByVal assNo As String, ByVal userState As Object)
            If (Me.Impresion_Hoja_Kit_RegistradaOperationCompleted Is Nothing) Then
                Me.Impresion_Hoja_Kit_RegistradaOperationCompleted = AddressOf Me.OnImpresion_Hoja_Kit_RegistradaOperationCompleted
            End If
            Me.InvokeAsync("Impresion_Hoja_Kit_Registrada", New Object() {assNo}, Me.Impresion_Hoja_Kit_RegistradaOperationCompleted, userState)
        End Sub
        
        Private Sub OnImpresion_Hoja_Kit_RegistradaOperationCompleted(ByVal arg As Object)
            If (Not (Me.Impresion_Hoja_Kit_RegistradaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Impresion_Hoja_Kit_RegistradaCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrinterDocument:Impresion_Hoja_Kit", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", ResponseElementName:="Impresion_Hoja_Kit_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Impresion_Hoja_Kit(ByVal assNo As String)
            Me.Invoke("Impresion_Hoja_Kit", New Object() {assNo})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Impresion_Hoja_KitAsync(ByVal assNo As String)
            Me.Impresion_Hoja_KitAsync(assNo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Impresion_Hoja_KitAsync(ByVal assNo As String, ByVal userState As Object)
            If (Me.Impresion_Hoja_KitOperationCompleted Is Nothing) Then
                Me.Impresion_Hoja_KitOperationCompleted = AddressOf Me.OnImpresion_Hoja_KitOperationCompleted
            End If
            Me.InvokeAsync("Impresion_Hoja_Kit", New Object() {assNo}, Me.Impresion_Hoja_KitOperationCompleted, userState)
        End Sub
        
        Private Sub OnImpresion_Hoja_KitOperationCompleted(ByVal arg As Object)
            If (Not (Me.Impresion_Hoja_KitCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Impresion_Hoja_KitCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrinterDocument:Pendiente_PDF", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", ResponseElementName:="Pendiente_PDF_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Pendiente_PDF() As <System.Xml.Serialization.XmlElementAttribute("return_value")> String
            Dim results() As Object = Me.Invoke("Pendiente_PDF", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Pendiente_PDFAsync()
            Me.Pendiente_PDFAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Pendiente_PDFAsync(ByVal userState As Object)
            If (Me.Pendiente_PDFOperationCompleted Is Nothing) Then
                Me.Pendiente_PDFOperationCompleted = AddressOf Me.OnPendiente_PDFOperationCompleted
            End If
            Me.InvokeAsync("Pendiente_PDF", New Object(-1) {}, Me.Pendiente_PDFOperationCompleted, userState)
        End Sub
        
        Private Sub OnPendiente_PDFOperationCompleted(ByVal arg As Object)
            If (Not (Me.Pendiente_PDFCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Pendiente_PDFCompleted(Me, New Pendiente_PDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrinterDocument:Printer_Label", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", ResponseElementName:="Printer_Label_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Printer_Label(ByVal tipoEtiqueta As String) As <System.Xml.Serialization.XmlElementAttribute("return_value")> String
            Dim results() As Object = Me.Invoke("Printer_Label", New Object() {tipoEtiqueta})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Printer_LabelAsync(ByVal tipoEtiqueta As String)
            Me.Printer_LabelAsync(tipoEtiqueta, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Printer_LabelAsync(ByVal tipoEtiqueta As String, ByVal userState As Object)
            If (Me.Printer_LabelOperationCompleted Is Nothing) Then
                Me.Printer_LabelOperationCompleted = AddressOf Me.OnPrinter_LabelOperationCompleted
            End If
            Me.InvokeAsync("Printer_Label", New Object() {tipoEtiqueta}, Me.Printer_LabelOperationCompleted, userState)
        End Sub
        
        Private Sub OnPrinter_LabelOperationCompleted(ByVal arg As Object)
            If (Not (Me.Printer_LabelCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Printer_LabelCompleted(Me, New Printer_LabelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrinterDocument:resolver", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", ResponseElementName:="resolver_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrinterDocument", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub resolver(ByVal xId As Integer, ByVal xError As String)
            Me.Invoke("resolver", New Object() {xId, xError})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub resolverAsync(ByVal xId As Integer, ByVal xError As String)
            Me.resolverAsync(xId, xError, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub resolverAsync(ByVal xId As Integer, ByVal xError As String, ByVal userState As Object)
            If (Me.resolverOperationCompleted Is Nothing) Then
                Me.resolverOperationCompleted = AddressOf Me.OnresolverOperationCompleted
            End If
            Me.InvokeAsync("resolver", New Object() {xId, xError}, Me.resolverOperationCompleted, userState)
        End Sub
        
        Private Sub OnresolverOperationCompleted(ByVal arg As Object)
            If (Not (Me.resolverCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent resolverCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Etiquetas_EnviosCompletedEventHandler(ByVal sender As Object, ByVal e As Etiquetas_EnviosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Etiquetas_EnviosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Etiquetas_GS1CompletedEventHandler(ByVal sender As Object, ByVal e As Etiquetas_GS1CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Etiquetas_GS1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Etiquetas_Kits_GS1CompletedEventHandler(ByVal sender As Object, ByVal e As Etiquetas_Kits_GS1CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Etiquetas_Kits_GS1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Etiquetas_KitsCompletedEventHandler(ByVal sender As Object, ByVal e As Etiquetas_KitsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Etiquetas_KitsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GTIN14_DCCompletedEventHandler(ByVal sender As Object, ByVal e As GTIN14_DCCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GTIN14_DCCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Impresion_AlbaranCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Impresion_EnvioCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Impresion_Etiqueta_Kit_EspecialCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Impresion_Etiqueta_KitCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Impresion_Etiquetas_EnvioCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Impresion_GS1CompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Impresion_Hoja_Kit_RegistradaCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Impresion_Hoja_KitCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Pendiente_PDFCompletedEventHandler(ByVal sender As Object, ByVal e As Pendiente_PDFCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Pendiente_PDFCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Printer_LabelCompletedEventHandler(ByVal sender As Object, ByVal e As Printer_LabelCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Printer_LabelCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub resolverCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
